import streamlit as st
import pandas as pd
import numpy as np
from pathlib import Path
import sys
sys.path.append("src")
from data_utils import load_data, build_features, make_target
from solar import solar_scenario

st.set_page_config(page_title="Electricity Consumption Intelligence",layout="wide")
st.title("Electricity Consumption Intelligence")
st.caption("Hansot Subdivision | Consumer Profiling • Classification • PCA • CBLOF • Solar")

uploaded=st.file_uploader("Upload permitted/anonymized Hansot Excel dataset",type=["xlsx","xls"])
if uploaded is None:
    st.info("Upload the permitted dataset to explore the dashboard.")
    st.stop()

df,months=load_data(uploaded)
df,first7,last3=build_features(df,months)
df,threshold=make_target(df)

st.sidebar.header("Filters")
tariffs=st.sidebar.multiselect("Tariff",sorted(df.TARRIF.dropna().unique()),default=sorted(df.TARRIF.dropna().unique()))
villages=st.sidebar.multiselect("Village",sorted(df.VILLAGE_NAME.dropna().unique()))
df=df[df.TARRIF.isin(tariffs)]
if villages: df=df[df.VILLAGE_NAME.isin(villages)]

tabs=st.tabs(["Overview","Consumption","Load Anomalies","PCA / Clusters","Solar"])

with tabs[0]:
    a,b,c,d=st.columns(4)
    a.metric("Consumers",f"{len(df):,}")
    b.metric("Avg monthly kWh",f"{df[months].mean().mean():,.1f}")
    c.metric("Solar consumers",f"{(df.SOLAR_CONSUMER=='Y').sum():,}")
    d.metric("Feeders",f"{df.FEEDER_NAME.nunique():,}")
    st.subheader("Average monthly consumption")
    st.line_chart(df[months].mean(axis=0))

with tabs[1]:
    st.subheader("Consumption by tariff")
    st.dataframe(df.groupby("TARRIF")[months].mean().T.round(1),use_container_width=True)
    st.subheader("Consumer statistics")
    st.dataframe(df[["Consumer Name","TARRIF","AREA","FEEDER_NAME","VILLAGE_NAME","CONTRACT_LOAD","train_avg","train_std","cv"]].sort_values("train_avg",ascending=False).head(100),use_container_width=True)

with tabs[2]:
    st.subheader("Contract-load benchmark")
    latest=months[-1]
    benchmark=df.CONTRACT_LOAD*8*31*.8
    ratio=df[latest]/benchmark.replace(0,np.nan)
    screen=pd.DataFrame({"Consumer":df["Consumer Name"],"Contract load kW":df.CONTRACT_LOAD,
                         "Latest kWh":df[latest],"Benchmark kWh":benchmark,"Consumption ratio":ratio})
    screen["Review flag"]=np.select([ratio<.25,ratio>1.5],
        ["Low-consumption anomaly—review required","High-consumption anomaly—review required"],
        default="Normal/insufficient evidence")
    st.dataframe(screen.sort_values("Consumption ratio",ascending=False).head(100),use_container_width=True)
    st.caption("The benchmark is an assumption-based review reference; it does not prove theft, meter fault or unauthorized load.")

with tabs[3]:
    st.subheader("PCA projection")
    st.write("The PCA plot is generated by the training pipeline and can be displayed from results/figures/pca_clusters.png when running locally.")
    pca_file=Path("results/figures/pca_clusters.png")
    if pca_file.exists(): st.image(str(pca_file),use_container_width=True)
    metric_file=Path("results/clustering_metrics.csv")
    if metric_file.exists(): st.dataframe(pd.read_csv(metric_file),use_container_width=True)

with tabs[4]:
    st.subheader("Preliminary rooftop solar scenario")
    annual=st.number_input("Annual consumption (kWh)",min_value=0.0,value=float(df[months].sum(axis=1).median()))
    capacity=st.slider("Solar capacity (kW)",3.0,20.0,3.0,.5)
    tariff=st.number_input("Tariff assumption (₹/kWh)",min_value=0.0,value=7.0)
    pricing_scenario=st.selectbox(
        "Pricing scenario",
        ["incremental_above_3kw", "all_capacity_above_3kw_rate"],
        format_func=lambda value: {
            "incremental_above_3kw": "3 kW base + incremental rate above 3 kW",
            "all_capacity_above_3kw_rate": "Entire system at above-3-kW rate",
        }[value],
    )
    sc=solar_scenario(annual,capacity,tariff=tariff,pricing_scenario=pricing_scenario)
    x,y,z,w=st.columns(4)
    x.metric("Generation",f"{sc['generation']:,.0f} kWh")
    y.metric("Net cost",f"₹{sc['net_cost']:,.0f}")
    z.metric("Annual net savings",f"₹{sc['annual_net_savings']:,.0f}")
    w.metric("Payback","N/A" if sc["payback"] is None else f"{sc['payback']:.1f} years")
    st.write(f"Exported electricity: {sc['export']:,.0f} kWh")
    st.warning("Scenario assumptions only. Technical feasibility requires rooftop area, shading, daytime load, tariff/export rules and site-specific yield.")
